# scripts/gen_build_info.py
Import("env")
from datetime import datetime, timezone

# PCのローカル時刻で "yyMMddHHmmss" を作る
now_local = datetime.now()
build_str = now_local.strftime("%y%m%d%H%M%S")
build_ver = now_local.strftime("%y%m%d%H.%M0")

header_path = "include/build_info.h"

content = f"""/**
 * @file build_info.h
 * @version {build_ver}
 * @note
 * Auto-generated by PlatformIO build script.
 * DO NOT EDIT.
 */

#ifndef BUILD_INFO_H
#define BUILD_INFO_H
// Auto-generated by PlatformIO build script. DO NOT EDIT.

#define BUILD_DATETIME "{build_str}"
#endif  /* BUILD_INFO_H */
"""

with open(header_path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"[gen] {header_path}: {build_str}")
