; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; version 26060619.530

[esp32_base]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_type = debug
extra_scripts = pre:scripts/gen_build_info.py
lib_ldf_mode = chain
build_flags =
	-DCORE_DEBUG_LEVEL=1
	-DUSE_ESPNOW
;	-DUSE_ESP32SERVO
	-DUSE_M5ATOMICMOTION
lib_deps =
	M5Unified=https://github.com/M5Stack/M5Unified
	M5GFX=https://github.com/M5Stack/M5GFX
	Arduino_JSON=arduino-libraries/Arduino_JSON@^0.2.0
	ESP32Servo=madhephaestus/ESP32Servo @ ^3.2.1
	M5AtomicMotion=https://github.com/m5stack/M5Atomic-Motion

[env:m5stack-nocsw]
extends =
	esp32_base
board = m5stack-core-esp32
board_build.partitions = min_spiffs.csv
build_flags =
	${esp32_base.build_flags}
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-core]
extends =
	esp32_base
board = m5stack-core-esp32
board_build.partitions = min_spiffs.csv
build_flags =
	${esp32_base.build_flags}
	-DUSE_DISP
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-stickcplus]
extends =
	esp32_base
board = m5stack-core-esp32
board_build.partitions = min_spiffs.csv
build_flags =
	${esp32_base.build_flags}
	-DUSE_DISP
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-atoms3]
extends =
	esp32_base
board = esp32-s3-devkitc-1
build_flags =
	${esp32_base.build_flags}
	-DUSE_DISP
	-DUSE_SHOWNEWS
	-DESP32S3
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-atoms3l]
extends =
	esp32_base
board = esp32-s3-devkitc-1
build_flags =
	${esp32_base.build_flags}
	-DESP32S3
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-atoms3r]
extends = esp32_base
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
build_flags =
	${esp32_base.build_flags}
	-DUSE_DISP
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-atoms3rc]
extends = esp32_base
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
build_flags =
	${esp32_base.build_flags}
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps =
	${esp32_base.lib_deps}

[env:m5stack-sticks3]
extends = esp32_base
board = esp32-s3-devkitc-1
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
	${esp32_base.build_flags}
	-DUSE_DISP
	-DESP32S3
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps =
	${esp32_base.lib_deps}
	M5PM1=https://github.com/m5stack/M5PM1

[env:m5stack-cores3]
extends = esp32_base
board = m5stack-cores3
build_flags =
	${esp32_base.build_flags}
	-DUSE_DISP
	-DESP32S3
	-mfix-esp32-psram-cache-issue
lib_deps =
	${esp32_base.lib_deps}
